config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :usertests
  devise_for :users

  root 'app#home'
  get 'admin', to: 'app#admin'
  # Rails.application.routes.draw do
  #   devise_for :users, controllers: {
  #     sessions: 'users/sessions'
  #   }
  # end
  get 'admin/profile', to: 'admin#profile'
  get 'admin/create_contact', to: 'admin#create_contact'
  get 'admin/contact_list', to: 'admin#contact_list'

  resources :users do
    resources :profiles, only: %i[new create edit update]
    resources :notes
    resources :contacts
  end

  get 'contacts/search', to: 'contacts#search'

  get 'admin/onboarding', to: 'profiles#onboarding'
  post 'admin/onboarding', to: 'profiles#create_onboarding'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Association
  belongs_to :user

  has_one_attached :avatar

  # Callbacks
  # Strip First Name and Last Name of spaces
  before_save do
    self.first_name = first_name.strip
    self.last_name = last_name.strip
  end

  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true

  # Methods
  def full_address
    "#{address}, #{city}, #{state} #{zip_code}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def avatar_attached?
    avatar.attached? ? avatar : 'avatar-3.png'
  end

end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  layout 'onboarding-layout', only: %i[onboarding create_onboarding]

  def new
    @profile = @user.build_profile
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = 'Your Profile was successfully created.'
      redirect_to admin_profile_path
    else
      respond_to do |format|
        format.js { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @profile = @user.profile
    respond_to do |format|
      format.js
    end
  end

  def update
    @profile = @user.profile
    if @profile.update(profile_params)
      flash[:success] = 'Your Profile was successfully updated.'
      redirect_to admin_profile_path
    else
      respond_to do |format|
        format.js { render :edit }
      end
    end
  end

  def onboarding
    if @user.profile.present?
      redirect_to admin_profile_url
    else
      @profile = @user.build_profile
    end
  end

  def create_onboarding

    if @user.profile.present?
      redirect_to admin_profile_url
    else
      @profile = @user.build_profile(profile_params)
      if @profile.save
        flash[:success] = 'Your Profile was successfully created.'
        redirect_to admin_profile_path
      else
        flash[:error] = 'Something went wrong.'
        render 'profiles/onboarding'
      end
    end
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :title, :company, :phone, :address, :city, :state,
                                    :zip_code, :avatar)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_edit.html.erb
<%= render "modal-form" %>

app/views/profiles/_error_profile.html.erb
<% if @user.profile.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@user.profile.errors.count, "error") %> prohibited this profile from being saved:</h4>

    <ul>
      <% @user.profile.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/profiles/_form.html.erb
<%= render 'error_profile' %>
<div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :first_name, class: "form-label" %><span class="w3-tiny"> *required</span>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="col-sm-6">
    <%= form.label :last_name, class: "form-label" %><span class="w3-tiny"> *required</span>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="col-sm-6">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="col-sm-6">
    <%= form.label :company, class: "form-label" %>
    <%= form.text_field :company, class: 'form-control' %>
  </div>

  <div class="col-12">
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_field :phone, class: 'form-control' %>
  </div>

  <div class="col-12">
    <%= form.label :address, class: "form-label" %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="col-md-5">
    <%= form.label :city, class: "form-label" %>
    <%= form.text_field :city, class: 'form-control' %>
  </div>

  <div class="col-md-4">
    <%= form.label :state, class: "form-label" %>
    <%= form.text_field :state, class: 'form-control' %>
  </div>

  <div class="col-md-3">
    <%= form.label :zip_code, class: "form-label" %>
    <%= form.text_field :zip_code, class: 'form-control' %>
  </div>
  <div class="col-md-3">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>
  <p>
    <%= form.submit class: "w-100 btn btn-primary btn-lg" %>
  </p>
</div>

app/views/profiles/_modal-form.html.erb
<div class="modal-content">
  <div class="modal-header">
    <% if @user.profile.id.nil? %>
      <h3 class="modal-title">Create Profile</h3>
    <% else %>
      <h3 class="modal-title">Edit Profile</h3>
    <% end %>
    <!--		<button type="button" class="btn close" data-dismiss="modal">x</button>-->
  </div>
  <div class="modal-body">
    <div class="">
      <!-- If Profile is nil, Create Profile Form  -->
      <% if @user.profile.nil? %>
        <%= form_with(model: [@user, @user.build_profile], local: false) do |form| %>
          <%= render "profiles/form", form: form %>
        <% end %>
      <% else %>
        <!-- If Profile is not nil, Edit Profile Form  -->
        <%= form_with(model: [@user, @user.profile], local: false) do |form| %>
          <%= render "profiles/form", form: form %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/_new.html.erb
<%= render "modal-form" %>

app/views/profiles/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'edit') %>")
$("#modal-window").modal("show");

app/views/profiles/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>")
$("#modal-window").modal("show");

app/views/profiles/onboarding.html.erb
<div class="w3-white w3-padding-16 w3-container w3-card-4 w3-section" style="margin-left:16px; margin-right: 16px;">
  <%= form_with(model: [@user, @profile], url: admin_onboarding_path) do |form| %>

    <div class="w3-text-indigo w3-padding-4">
      <h2>Create Your Profile</h2>
    </div>

    <%= render 'error_profile' %>

    <div class="w3-margin-top">
      <div class="w3-row">
        <div class="w3-col l6 w3-margin-bottom w3-padding-8">
          <%= form.label :first_name, class: "form-label" %>
          <span class="w3-tiny"> *required</span>
          <%= form.text_field :first_name, class: 'w3-input contactFormLength' %>
        </div>
        <div class="w3-col l6 w3-margin-bottom w3-padding-8">
          <%= form.label :last_name, class: "form-label" %><span class="w3-tiny"> *required</span>
          <%= form.text_field :last_name, class: 'w3-input contactFormLength' %>
        </div>
      </div>
      <div class="w3-row">
        <div class="w3-margin-bottom w3-padding-8 w3-col l6">
          <%= form.label :title, class: "form-label" %>
          <%= form.text_field :title, class: 'w3-input contactFormLength' %>
        </div>
        <div class="w3-margin-bottom w3-padding-8 w3-col l6">
          <%= form.label :company, class: "form-label" %>
          <%= form.text_field :company, class: 'w3-input contactFormLength' %>
        </div>
      </div>
      <div>
        <div class="w3-margin-bottom w3-padding-8 w3-col l12">
          <%= form.label :phone, class: "form-label" %>
          <%= form.text_field :phone, class: 'w3-input contactFormLength' %>
        </div>
      </div>
      <div class="w3-margin-bottom w3-padding-8">
        <%= form.label :address, class: "form-label" %>
        <%= form.text_field :address, class: 'w3-input contactFormLength' %>
      </div>
      <div class="w3-row">
        <div class="w3-margin-bottom w3-padding-8 w3-col l4">
          <%= form.label :city, class: "form-label" %>
          <%= form.text_field :city, class: 'w3-input contactFormLength' %>
        </div>
        <div class="w3-margin-bottom w3-padding-8 w3-col l4">
          <%= form.label :state, class: "form-label" %>
          <%= form.text_field :state, class: 'w3-input contactFormLength' %>
        </div>
        <div class="w3-margin-bottom w3-padding-8 w3-col l4">
          <%= form.label :zip_code, class: "form-label" %>
          <%= form.text_field :zip_code, class: 'w3-input contactFormLength' %>
        </div>
      </div>
      <div class="w3-margin-bottom w3-padding-8">
        <%= form.label :avatar, "Profile Picture" %>
        <%= form.file_field :avatar, class: 'w3-input contactFormLength' %>
      </div>
    </div>
    <p class="w3-text-red"></p>
    <div class="w3-margin-bottom w3-padding-16 contactFormLength">
      <%= form.submit class: "w3-btn buttonColorTheme w3-left" %>
    </div>
  <% end %>
</div>