config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :usertests
  devise_for :users

  root 'app#home'
  get 'admin', to: 'app#admin'
  # Rails.application.routes.draw do
  #   devise_for :users, controllers: {
  #     sessions: 'users/sessions'
  #   }
  # end
  get 'admin/profile', to: 'admin#profile'
  get 'admin/create_contact', to: 'admin#create_contact'
  get 'admin/contact_list', to: 'admin#contact_list'

  resources :users do
    resources :profiles, only: %i[new create edit update]
    resources :notes
    resources :contacts
  end

  get 'contacts/search', to: 'contacts#search'

  get 'admin/onboarding', to: 'profiles#onboarding'
  post 'admin/onboarding', to: 'profiles#create_onboarding'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/contact_list.html.erb
<% content_for :sub_title do %> Contact List
<% end %>

<div class="w3-row-padding w3-stretch">
  <div class="w3-col l3">
    <div class="w3-card w3-container w3-white w3-padding-16 ">
      <h4>Sort by</h4>
      <input type="radio" name="sortContact" value="firstName"> <label for="firstName">First Name</label><br>

      <input type="radio" name="sortContact" value="lastName"> <label for="lastName">Last Name</label><br>

      <input type="radio" name="sortContact" value="title"> <label for="title">Title</label><br>

      <input type="radio" name="sortContact" value="company"> <label for="company">Company</label><br>

      <hr>
      <h4>Filter by</h4>
      <input type="checkbox" name="favorite" value="favorite">
      <label for="favorite">Favorite</label>
    </div>
  </div>
  <div class="w3-col l9">
    <div class="w3-card w3-white w3-responsive">
      <table class="w3-table w3-striped w3-centered w3-bordered w3-card">
        <tr class="w3-indigo w3-padding-32">
          <th>First Name</th>
          <th>Last Name</th>
          <th>Title</th>
          <th>Company</th>
          <th>Favorite</th>
        </tr>
        <tr>
          <td class="ng-binding">Frank</td>
          <td class="ng-binding">Smith</td>
          <td class="ng-binding">Visual Designer</td>
          <td class="ng-binding">Tesla</td>
          <td class="ng-binding"></td>
        </tr>
        <tr>
          <td class="ng-binding">Erik</td>
          <td class="ng-binding">Brooks</td>
          <td class="ng-binding">VP of Software</td>
          <td class="ng-binding">Google</td>
          <td class="ng-binding"></td>
        </tr>
        <tr>
          <td class="ng-binding">Dianna</td>
          <td class="ng-binding">Philipsson</td>
          <td class="ng-binding">Information Systems Manager</td>
          <td class="ng-binding">Nike</td>
          <td class="ng-binding"></td>
        </tr>
        <tr>
          <td class="ng-binding">Edward</td>
          <td class="ng-binding">Wells</td>
          <td class="ng-binding">Web Strategist</td>
          <td class="ng-binding">Apple</td>
          <td class="ng-binding">true</td>
        </tr>
        <tr>
          <td class="ng-binding">Freddie</td>
          <td class="ng-binding">Dixon</td>
          <td class="ng-binding">Data Scientist</td>
          <td class="ng-binding">Ubisoft</td>
          <td class="ng-binding">true</td>
        </tr>
        <tr>
          <td class="ng-binding">Adam</td>
          <td class="ng-binding">Jenkins</td>
          <td class="ng-binding">Marketing Manager</td>
          <td class="ng-binding">Adobe</td>
          <td class="ng-binding"></td>
        </tr>
        <tr>
          <td class="ng-binding">Amy</td>
          <td class="ng-binding">Gray</td>
          <td class="ng-binding">Accountant</td>
          <td class="ng-binding">Canon</td>
          <td class="ng-binding">true</td>
        </tr>
        <tr>
          <td class="ng-binding">Sophie</td>
          <td class="ng-binding">Bailey</td>
          <td class="ng-binding">Front End Developer</td>
          <td class="ng-binding">Oracle</td>
          <td class="ng-binding">true</td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/create_contact.html.erb
<% content_for :sub_title do %> Create Contact
<% end %>

<div class="w3-white w3-padding-16 w3-container w3-card w3-section">
  <form action="" name="Form" class="">
    <div class="w3-margin-top">
      <div class="w3-margin-bottom w3-padding-8">
        <label for="favorite">
          <input type="checkbox" placeholder="Favorite" class="" name="favorite">
          <i class="fa fa-thumbs-up fa-fw w3-large w3-text-black"></i>Favorite</label><br>
      </div>
      <div class="w3-row">
        <div class="w3-col l6 w3-margin-bottom w3-padding-8">
          <label for="user.firstName"><i class="fa fa-user fa-fw w3-large w3-text-black"></i></label>
          <input type="text" class="w3-input contactFormLength" placeholder="First Name" name="user.firstName" required="">
        </div>
        <div class="w3-col l6 w3-margin-bottom w3-padding-8">
          <label for="user.lastName"><i class="fa fa-user fa-fw w3-large w3-text-black"></i></label>
          <input type="text" class="w3-input contactFormLength" placeholder="Last Name" name="user.lastName" required="">
        </div>
      </div>
      <div class="w3-row">
        <div class="w3-margin-bottom w3-padding-8 w3-col l6">
          <label for="title"><i class="fa fa-suitcase fa-fw w3-large w3-text-black"></i></label>
          <input type="text" class="w3-input contactFormLength" placeholder="Title" name="title">
        </div>
        <div class="w3-margin-bottom w3-padding-8 w3-col l6">
          <label for="company"><i class="fa fa-building fa-fw w3-large w3-text-black"></i></label>
          <input type="text" class="w3-input contactFormLength" placeholder="Company" name="company">
        </div>
      </div>
      <div>
        <div class="w3-margin-bottom w3-padding-8 w3-col l6">
          <label for="phone"><i class="fa fa-phone fa-fw w3-large w3-text-black"></i></label>
          <input type="text" class="w3-input contactFormLength" placeholder="Phone" name="phone">
        </div>
        <div class="w3-margin-bottom w3-padding-8 w3-col l6">
          <label for="email"><i class="fa fa-envelope fa-fw w3-large w3-text-black"></i></label>
          <input type="text" class="w3-input contactFormLength" placeholder="Email" name="email">
        </div>
      </div>
      <div class="w3-margin-bottom w3-padding-8">
        <label for="address"><i class="fa fa-location-arrow fa-fw w3-large w3-text-black"></i></label>
        <input type="text" class="w3-input contactFormLength" placeholder="Address" name="address">
      </div>
      <div class="w3-margin-bottom w3-padding-8">
        <label for="avatar"><i class="fa fa-image fa-fw w3-large w3-text-black"></i> Profile Picture</label>
        <input type="file" class="w3-input contactFormLength" data-file="user.avatar" name="avatar">
      </div>
    </div>
    <div class="w3-margin-bottom w3-padding-16 contactFormLength">
      <button type="submit" class="w3-btn buttonColorTheme w3-left">Add Contact</button>
      <button type="reset" class="w3-btn buttonColorTheme w3-right">Clear</button>
    </div>
  </form>
</div>

app/views/admin/profile.html.erb
<% content_for :sub_title do %> My Profile
<% end %>

<div class="w3-row-padding w3-stretch">
  <!-- Profile Side -->
  <div class="w3-col l4 w3-margin-bottom" id="profile">
    <div class="w3-white w3-text-black w3-card">
      <br>
      <% if @user.profile.present? %>
        <h3 class="w3-center"><%= @user.profile.full_name %></h3>
      <% else %>
        <h3 class="w3-center">Create Your Profile</h3>
      <% end %>
      <div class="w3-center w3-container">
        <% if @user.profile %>
          <%= image_tag(@user.profile.avatar_attached?, class: "w3-card w3-padding mainAvatarSize") %>
        <% end %>
        <%#= form_with(model: [@user, @user.profile], class: "w3-center") do |form| %>
        <!--          <div class="w3-container w3-margin-top">-->
        <%#= form.file_field :avatar %>
        <%#= form.submit class: "w-100 btn btn-primary btn-lg" %>
        <!--          </div>-->
        <%# end %>
      </div>
      <hr>
      <div class="w3-center w3-container w3-row">
        <div class="w3-col l12 s12">
          <% if @user.profile.nil? %>
            <%= link_to new_user_profile_path(@user), { :remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window' } do %>
              <i class="fa fa-pencil w3-text-green" style="font-size:25px; cursor:pointer"></i>
              <span>Create Profile</span>
            <% end %>

          <% else %>
            <%= link_to edit_user_profile_path(@user, @user.profile), { :remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window' } do %>
              <i class="fa fa-pencil w3-text-green" style="font-size:25px; cursor:pointer"></i>
              <span>Edit Profile</span>
            <% end %>

          <% end %>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <p>
          <i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-indigo"></i><span><%= @user.profile.title if @user.profile.present? %></span>
        </p>
        <p>
          <i class="fa fa-building fa-fw w3-margin-right w3-large w3-text-indigo"></i><span><%= @user.profile.company if @user.profile.present? %></span>
        </p>
        <p>
          <i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-indigo"></i><span><%= @user.profile.phone if @user.profile.present? %></span>
        </p>
        <p>
          <i class="fa fa-location-arrow fa-fw w3-margin-right w3-large w3-text-indigo"></i><span><%= @user.profile.full_address if @user.profile.present? %></span>
        </p>
      </div>
    </div>
  </div>
  <!-- End Profile Side -->

  <!-- Content Side -->
  <div class="w3-col l8">

    <!-- Add Notes Tab -->
    <div class="w3-container w3-card-2 w3-white w3-margin-bottom">
      <h2 class="w3-text-indigo w3-padding-16">Add A Note</h2>
      <%= form_with model: [@user, @user.notes.build] do |form| %>
        <%= render "notes/error_note", note: @note %>
        <p>
          <%= form.text_area :content, class: "w3 - margin - bottom w3 - padding noteTabText ", cols: "80", rows: "5" %>
        </p>
        <p>
          <%= form.submit "Add Note ", class: "w3 - btn buttonColorTheme " %>
        </p>
      <% end %>
    </div>
    <!-- End Notes Tab -->

    <!-- History Tab -->
    <div class="w3-container w3-card-2 w3-white w3-margin-bottom" id="reminder">
      <h2 class="w3-text-indigo w3-padding-16">Note History</h2>

      <% if @user.notes.present? %>
        <% @user.notes.each do |note| %>
          <% unless note.id.nil? %>
            <div class="w3-container w3-card w3-margin-bottom panelCardNote alert alert-dismissible fade show" role="alert">
              <%= link_to user_note_path(note.user, note), method: :delete, data: { confirm: "You are about to delete this note.Are you sure? " } do %>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" id="delete_note_button"></button>
              <% end %>
              <h5 class="w3-opacity"><b>Note.</b>
                <span class="time-ago">Posted <%= time_ago_in_words(note.created_at) %> ago.</span></h5>
              <p><%= note.content %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <!-- End History Tab -->
  </div>

  <div id="modal-window" class="modal hide fade" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
  <br>
  <br>
</div>