config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :usertests
  devise_for :users

  root 'app#home'
  get 'admin', to: 'app#admin'
  # Rails.application.routes.draw do
  #   devise_for :users, controllers: {
  #     sessions: 'users/sessions'
  #   }
  # end
  get 'admin/profile', to: 'admin#profile'
  get 'admin/create_contact', to: 'admin#create_contact'
  get 'admin/contact_list', to: 'admin#contact_list'

  resources :users do
    resources :profiles, only: %i[new create edit update]
    resources :notes
    resources :contacts
  end

  get 'contacts/search', to: 'contacts#search'

  get 'admin/onboarding', to: 'profiles#onboarding'
  post 'admin/onboarding', to: 'profiles#create_onboarding'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true

  # Will paginate per 5 pages
  self.per_page = 10

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  layout 'admin-layout'

  def index
    if params.key?(:favorite)
      case params[:favorite]
      when '1'
        @contacts = @user.contacts.where(favorite: true).paginate(page: params[:page])
      when '0'
        @contacts = @user.contacts.where(favorite: false).paginate(page: params[:page])
      end
    else
      @contacts = @user.contacts.paginate(page: params[:page])
    end
  end

  def show
    @contact = @user.contacts.find(params[:id])
  end

  def new
    @contact = @user.contacts.build
  end

  def create
    @contact = @user.contacts.build(contact_params)
    if @contact.save
      flash[:success] = 'Your Contact was successfully created.'
      redirect_to user_contacts_path
    else
      flash.now[:error] = 'Something went wrong.'
      render :new
    end
  end

  def edit
    @contact = @user.contacts.find(params[:id])
  end

  def update
    @contact = @user.contacts.find(params[:id])
    if @contact.update(contact_params)
      flash[:success] = 'Your Contact was successfully updated.'
      redirect_to user_contact_path
    else
      flash[:error] = 'Something went wrong.'
      render 'edit'
    end
  end

  def destroy
    @contact = @user.contacts.find(params[:id])
    @contact.destroy
    flash[:success] = 'Your contact was successfully deleted.'
    redirect_to user_contacts_url
  end

  def search
    @query = params[:query]
    @contacts = @user.contacts.where('first_name like ? or last_name like ?', "%#{@query}%", "%#{@query}%")
                     .paginate(page: params[:page])
  end

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :phone, :address, :title, :company, :favorite,
                                    :user_id)
  end
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
  def is_favorite?(boolean)
    boolean ? '&#10004;	'.html_safe : ''
  end
end

app/views/contacts/_display_contacts.html.erb
<div class="w3-row-padding w3-stretch">
  <div class="w3-col l3">
    <div class="w3-card w3-container w3-white w3-padding-16 w3-margin-bottom ">
      <!--      <h4>Sort by</h4>-->

      <!--      <input type="radio" name="sortContact" value="firstName"> <label for="firstName">First Name</label><br>-->

      <!--      <input type="radio" name="sortContact" value="lastName"> <label for="lastName">Last Name</label><br>-->

      <!--      <input type="radio" name="sortContact" value="title"> <label for="title">Title</label><br>-->

      <!--      <input type="radio" name="sortContact" value="company"> <label for="company">Company</label><br>-->

      <!--      <hr>-->
      <h4>Filter by</h4>
      <%= form_with url: user_contacts_path(@user, @contact), method: :get do |form| %>
        <%= form.check_box :favorite %>
        <%= form.label :favorite %>
        <%= form.submit %>
      <% end %>
      <%= form_with url: user_contacts_path(@user, @contact), class: "w3-margin-top", method: :get do |form| %>
        <%= form.submit "Reset", class: "w3-btn buttonColorTheme" %>
      <% end %>
    </div>

  </div>
  <div class="w3-col l9">
    <div class="w3-card w3-white w3-responsive">
      <table class="w3-table w3-striped w3-centered w3-bordered w3-card">
        <tr class="w3-indigo w3-padding-32">
          <th>First Name</th>
          <th>Last Name</th>
          <th>Title</th>
          <th>Company</th>
          <th>Favorite</th>
          <th>Contact Profile</th>
        </tr>
        <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.first_name %></td>
            <td><%= contact.last_name %></td>
            <td><%= contact.title %></td>
            <td><%= contact.company %></td>
            <td><%= is_favorite?(contact.favorite) %></td>
            <td><%= link_to "<i class='fa fa-id-card'></i>".html_safe, user_contact_path(@user, contact) %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="w3-margin-top">
      <%= will_paginate @contacts, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer, previous_label: '&laquo;', next_label: '&raquo;' %>
    </div>
  </div>


</div>

app/views/contacts/_error_contact.html.erb
<!--	Error Form For Notes -->
<% if contact.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h4>
    <ul>
      <% contact.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<!--End Error Form For Notes -->

app/views/contacts/_form.html.erb
<div class="w3-white w3-padding-16 w3-container w3-card w3-section">
  <%= render "contacts/error_contact", contact: @contact %>
  <div class="w3-margin-top">
    <div class="w3-margin-bottom w3-padding-8">
      <%= form.check_box :favorite %>
      <i class="fa fa-thumbs-up fa-fw w3-large w3-text-black"></i><%= form.label :favorite %>
    </div>
    <div class="w3-row">
      <div class="w3-col l6 w3-margin-bottom w3-padding-8">
        <%= form.label :first_name, '<i class="fa fa-user fa-fw w3-large w3-text-black"></i><span class="w3-tiny">*required</span>'.html_safe %>
        <%= form.text_field :first_name, class: "w3-input contactFormLength", placeholder: "First Name" %>
      </div>
      <div class="w3-col l6 w3-margin-bottom w3-padding-8">
        <%= form.label :last_name, '<i class="fa fa-user fa-fw w3-large w3-text-black"></i><span class="w3-tiny">*required</span>'.html_safe %>
        <%= form.text_field :last_name, class: "w3-input contactFormLength", placeholder: "Last Name" %>
      </div>
    </div>
    <div class="w3-row">
      <div class="w3-margin-bottom w3-padding-8 w3-col l6">
        <%= form.label :title, '<i class="fa fa-suitcase fa-fw w3-large w3-text-black"></i>'.html_safe %>
        <%= form.text_field :title, class: "w3-input contactFormLength", placeholder: "Title" %>
      </div>
      <div class="w3-margin-bottom w3-padding-8 w3-col l6">
        <%= form.label :company, '<i class="fa fa-building fa-fw w3-large w3-text-black"></i>'.html_safe %>
        <%= form.text_field :company, class: "w3-input contactFormLength", placeholder: "Company" %>
      </div>
    </div>
    <div>
      <div class="w3-margin-bottom w3-padding-8 w3-col l6">
        <%= form.label :phone, '<i class="fa fa-phone fa-fw w3-large w3-text-black"></i>'.html_safe %>
        <%= form.text_field :phone, class: "w3-input contactFormLength", placeholder: "Phone" %>
      </div>
      <div class="w3-margin-bottom w3-padding-8 w3-col l6">
        <%= form.label :email, '<i class="fa fa-envelope fa-fw w3-large w3-text-black"></i>'.html_safe %>
        <%= form.text_field :email, class: "w3-input contactFormLength", placeholder: "Email" %>
      </div>
    </div>
    <div class="w3-margin-bottom w3-padding-8">
      <%= form.label :address, '<i class="fa fa-location-arrow fa-fw w3-large w3-text-black"></i>'.html_safe %>
      <%= form.text_field :address, class: "w3-input contactFormLength", placeholder: "Address" %>
    </div>
  </div>
  <div class="w3-margin-bottom w3-padding-16 contactFormLength">
    <%= form.submit class: "w3-btn buttonColorTheme w3-left" %>
  </div>
</div>

app/views/contacts/edit.html.erb
<% content_for :sub_title do %>
  Edit Contact
<% end %>

<%= link_to :back, class: " w3-margin-bottom" do %>
  <button class="w3-btn buttonColorTheme">Back</button>
<% end %>

<%= form_with model: [@user, @contact] do |form| %>
  <%= render 'form', form: form %>
<% end %>

app/views/contacts/index.html.erb
<% content_for :sub_title do %> Contact List
<% end %>

<%= render 'contacts/display_contacts' %>

app/views/contacts/new.html.erb
<% content_for :sub_title do %> Create Contact
<% end %>

<%= link_to :back, class: " w3-margin-bottom" do %>
  <button class="w3-btn buttonColorTheme">Back</button>
<% end %>

<%= form_with model: [@user, @user.contacts.build] do |form| %>
  <%= render 'form', form: form %>
<% end %>

app/views/contacts/search.html.erb
<% content_for :sub_title do %>
  Search
<% end %>

<div class="w3-section">
  <%= pluralize(@contacts.count, "query") %> found for <b><%= @query %></b>.
</div>
<%= render 'contacts/display_contacts' %>

app/views/contacts/show.html.erb
<% content_for :sub_title do %>
  View Contact
<% end %>

<div class="w3-row-padding w3-stretch">
  <!-- Profile Side -->
  <div class="w3-col l4 w3-margin-bottom" id="profile">
    <div class="w3-white w3-text-black w3-card">
      <br>
      <h3 class="w3-center"><%= @contact.full_name %></h3>
      <!--			<div class="w3-center w3-container">-->
      <!--				<img src="" alt="Avatar" class="w3-card w3-padding mainAvatarSize">-->
      <!--			</div>-->
      <hr>
      <div class="w3-center w3-container w3-row">
        <div class="w3-col l4 s4">
          <%= link_to edit_user_contact_path(@user, @contact) do %>
            <i class="fa fa-pencil w3-text-green" style="font-size:25px; cursor:pointer"></i><br><br>
            <span>Edit Contact</span>
          <% end %>
        </div>
        <div class="w3-col l4 s4">
          <i class="fa fa-thumbs-up favoriteThumb <%= "w3-text-red" if @contact.favorite == true %>" id="favorite"></i><br><br>
          <span>Favorite</span>
        </div>
        <div class="w3-col l4 s4">
          <%= link_to user_contact_path(@user, @contact), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa fa-trash w3-text-orange" style="font-size:25px; cursor:pointer;"></i><br><br>
            <span>Delete Contact</span>
          <% end %>
        </div>
      </div>
      <hr>
      <div class="w3-container">
        <p>
          <i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-indigo"></i><span><%= @contact.title %></span>
        </p>
        <p>
          <i class="fa fa-building fa-fw w3-margin-right w3-large w3-text-indigo"></i><span><%= @contact.company %></span>
        </p>
        <p>
          <i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-indigo"></i><span><%= @contact.phone %></span>
        </p>
        <p>
          <i class="fa fa-location-arrow fa-fw w3-margin-right w3-large w3-text-indigo"></i><span><%= @contact.address %></span>
        </p>
        <p>
          <span><%= "<i class='fa fa-thumbs-up fa-fw w3-margin-right w3-large w3-text-indigo'></i>".html_safe + @contact.first_name + " is a favorite contact" if @contact.favorite == true %></span>
        </p>
      </div>
    </div>
  </div>
  <!-- End Profile Side -->

  <!-- Side Information -->
  <div class="w3-col l8 w3-margin-bottom">
    <div class="w3-container w3-card w3-white">
      <h2 class="w3-text-grey w3-padding-16">
        <i class="fa fa-id-card fa-fw w3-margin-right w3-xxlarge w3-text-black"></i>Your Contact
        - <%= @contact.full_name %>
      </h2>
      <div class="w3-container">
        <h5 class="w3-opacity"><b>First Name:</b> <span class="w3-medium"><%= @contact.first_name %></span></h5>

      </div>
      <div class="w3-container">
        <h5 class="w3-opacity"><b>Last Name:</b> <span class="w3-medium"><%= @contact.last_name %></span></h5>

      </div>
      <div class="w3-container">
        <h5 class="w3-opacity"><b>Email:</b> <span class="w3-medium"><%= @contact.email %></span></h5>
      </div>
      <div class="w3-container">
        <h5 class="w3-opacity"><b>Phone:</b> <span class="w3-medium"><%= @contact.phone %></span></h5>
      </div>
      <div class="w3-container">
        <h5 class="w3-opacity"><b>Address:</b> <span class="w3-medium"><%= @contact.address %></span></h5>
      </div>
      <div class="w3-container">
        <h5 class="w3-opacity"><b>Title:</b> <span class="w3-medium"><%= @contact.title %></span></h5>
      </div>
      <div class="w3-container">
        <h5 class="w3-opacity"><b>Company:</b> <span class="w3-medium"><%= @contact.company %></span></h5>
      </div>
      <div class="w3-container">
        <h5 class="w3-opacity"><b>Contact Created:</b>
          <span class="w3-medium">You created this contact <%= time_ago_in_words(@contact.created_at) %>
            ago on <%= @contact.created_at.strftime("%B %d, %Y") %>.</span></h5>
      </div>
    </div>
  </div>
  <!-- End Side Information -->
</div>