config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :usertests
  devise_for :users

  root 'app#home'
  get 'admin', to: 'app#admin'
  # Rails.application.routes.draw do
  #   devise_for :users, controllers: {
  #     sessions: 'users/sessions'
  #   }
  # end
  get 'admin/profile', to: 'admin#profile'
  get 'admin/create_contact', to: 'admin#create_contact'
  get 'admin/contact_list', to: 'admin#contact_list'

  resources :users do
    resources :profiles, only: %i[new create edit update]
    resources :notes
    resources :contacts
  end

  get 'contacts/search', to: 'contacts#search'

  get 'admin/onboarding', to: 'profiles#onboarding'
  post 'admin/onboarding', to: 'profiles#create_onboarding'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-primary  alert-dismissible fade show mb-3" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<hr class="featurette-divider">
<footer class="container">
  <p class="float-end"><a href="#">Back to top</a></p>
  <p>© 2021 Krishna Diamesso</p>
</footer>

app/views/layouts/_navbar.html.erb
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
          <use xlink:href="#bootstrap"></use>
        </svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 ">
        <li><%= link_to 'Home', root_path, class: "nav-link px-2 text-white" %></li>
        <% if user_signed_in? %>
          <%= link_to 'To Dashboard', admin_profile_path, class: "nav-link px-2 text-white" %>
        <% end %>
      </ul>

      <div class="text-end">
        <% if user_signed_in? %>
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn btn-warning", type: "button" %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: "btn btn-outline-light me-2", type: "button" %>
          <%= link_to 'Sign-up', new_user_registration_path, class: "btn btn-warning", type: "button" %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="position-sticky pt-3">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to "<i class='fa fa-user-circle'></i> My Profile".html_safe, admin_profile_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "<i class='fa fa-users'></i> My Contacts".html_safe, user_contacts_path(@user), class: "nav-link" %>
      </li>
      <hr>
      <li class="nav-item">
        <%= link_to "<i class='fa fa-cogs'></i> Settings".html_safe, edit_user_registration_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/admin-layout.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kontakt - Dashboard</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag 'admin/admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- W3 CSS -->
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <%= stylesheet_link_tag 'admin/main', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'profiles', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>
<body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <%= link_to 'Kontakt', admin_profile_path, class: "navbar-brand col-md-3 col-lg-2 me-0 px-3" %>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- Search Bar -->
  <%= form_with url: contacts_search_path, method: :get, class: "d-flex form-control-dark w-100" do |form| %>
    <%= form.text_field :query, placeholder: "Search", class: "form-control form-control-dark w-100" %>
  <% end %>
  <!-- End Search Bar -->
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>
</header>


<div class="container-fluid">
  <div class="row">
    <%= render "layouts/sidebar" %>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard -<%= content_for :sub_title %></h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <%= link_to 'My Profile', admin_profile_path, class: "btn btn-sm btn-outline-secondary" %>
            <%= link_to 'Contact List', user_contacts_path(@user), class: "btn btn-sm btn-outline-secondary" %>
            <%= link_to 'Create Contact', new_user_contact_path(@user), class: "btn btn-sm btn-outline-secondary" %>
          </div>
        </div>
      </div>
      <%= render "layouts/flash" %>
      <%= yield %>
    </main>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kontakt2</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= content_for :asset_css %>
</head>

<body>
<%= render "layouts/navbar" %>
<%= render "layouts/flash" %>
<%= yield %>
</body>
</html>

app/views/layouts/onboarding-layout.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kontakt - Dashboard</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag 'admin/admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- W3 CSS -->
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <%= stylesheet_link_tag 'admin/main', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'profiles', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>
<body>

<div class="container-fluid">
  <div class="row">
    <main class="col-md-12 ms-sm-auto col-lg-12 px-md-12 w3-margin-top">
      <%= render "layouts/flash" %>
      <%= yield %>
    </main>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>

</body>
</html>